-- size of our actual window
WINDOW_WIDTH = 680
WINDOW_HEIGHT = 710


-- size we're emulating with push
VIRTUAL_WIDTH = 224
VIRTUAL_HEIGHT = 256


--Player Constants
TANK_MOVE_SPEED = 200


--Bullet's Objects Contants
BULLET_UP_SPEED = -200
BULLET_DOWN_SPEED = 150

-- Alien's constants
ALIEN_X_SPEED = 50
ALIEN_Y_SPEED = 60

ALIEN_Y_OFFSET = 10
ALIEN_X_OFFSET = 10

SQUAD_ROWS = 3
SQUAD_COLUMNS = 8
SQUAD_TOTAL_UNITS = SQUAD_ROWS * SQUAD_COLUMNS